# Generated by Django 3.0.4 on 2020-03-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='region',
            field=models.CharField(choices=[('Scotland', 'Scotland'), ('North', 'North'), ('Midlands', 'Midlands'), ('South', 'South'), ('Ireland', 'Ireland')], default='Midlands', max_length=10),
        ),
    ]
