# Generated by Django 3.0.4 on 2020-03-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20200310_1509'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='wrestlers',
        ),
        migrations.AddField(
            model_name='promotion',
            name='wrestlers',
            field=models.ManyToManyField(blank=True, null=True, related_name='promotions', to='people.Wrestler'),
        ),
    ]
