# Generated by Django 3.0.4 on 2020-03-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20200310_1519'),
        ('world', '0002_auto_20200310_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='wrestlers',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='people.Wrestler'),
        ),
    ]
