# Generated by Django 3.0.4 on 2020-03-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20200310_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fighters', models.ManyToManyField(blank=True, related_name='matches', to='world.Wrestler')),
                ('won_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='world.Wrestler')),
            ],
        ),
    ]
