# Generated by Django 3.0.4 on 2020-03-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20200310_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='movetype',
            new_name='move_type',
        ),
    ]
