# Generated by Django 3.0.4 on 2020-03-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20200310_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='age',
        ),
        migrations.RemoveField(
            model_name='move',
            name='height',
        ),
    ]
