# Generated by Django 3.0.4 on 2020-03-10 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20200310_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='age',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='height',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(220)]),
        ),
    ]
