# Generated by Django 3.0.4 on 2020-03-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20200310_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrestler',
            name='moves',
        ),
        migrations.AddField(
            model_name='wrestler',
            name='moves',
            field=models.ManyToManyField(blank=True, null=True, related_name='known_moves', to='people.Move'),
        ),
    ]
