# Generated by Django 3.0.4 on 2020-03-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20200310_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='moves',
            field=models.ManyToManyField(blank=True, related_name='known_moves', to='people.Move'),
        ),
    ]
